// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectOnMvc.Models;

namespace ProjectOnMvc.Migrations.Item
{
    [DbContext(typeof(ItemContext))]
    [Migration("20200130084859_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectOnMvc.Models.Item", b =>
                {
                    b.Property<int>("Cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Subid")
                        .HasColumnType("int");

                    b.Property<string>("Subname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("itemid")
                        .HasColumnType("int");

                    b.Property<string>("itemname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("itemprice")
                        .HasColumnType("float");

                    b.HasKey("Cid");

                    b.ToTable("item");
                });
#pragma warning restore 612, 618
        }
    }
}
